#!/usr/bin/env bash
# code-intel-init: version=2.4.1 body=10794b468cd6eb57bea1a2360a82c54dd3c9cc33495d41457090f1f4a722ea5a
#
# refresh-intel.sh — re-index and audit this project's code intelligence.
#
# ---------------------------------------------------------------------------
# READ THIS FIRST if you did not set this up — humans and coding agents alike.
# ---------------------------------------------------------------------------
#
# This is a LOCAL DEVELOPER TOOL. It is not part of this project's build, its
# test suite or its CI, and no application code depends on it. It keeps two
# code-search indexes fresh so AI coding agents can navigate the repository:
# a GitNexus knowledge graph and a GrepAI semantic index.
#
# It is GENERATED by `code-intel-init`, which lives OUTSIDE this repository
# (normally ~/.local/bin). The stamp on line 2 is a version and a hash of the
# rest of this file: code-intel-init regenerates this script when it is out of
# date, and leaves it alone once you edit it. Prefer changing code-intel-init.
#
# It needs a stack that is NOT part of this repository and that `npm install`
# does not provide: the `grepai` and `gitnexus` CLIs, a running qdrant (HTTP
# and gRPC) and a running ollama with one embedding model pulled.
#
# ---------------------------------------------------------------------------
# On a machine that never ran code-intel-init, THIS SCRIPT WILL FAIL — and
# that failure is EXPECTED AND HARMLESS.
# ---------------------------------------------------------------------------
#
# It stops before touching anything and exits 1 with
#
#   [ERROR: refresh-intel preflight found N unmet dependencies — nothing was indexed]
#
# That message says nothing about the health of this project's code. Do NOT
# "fix" the repository in response to it, and do NOT add these services to the
# project's dependencies, CI or docker-compose.
#
# If you are a coding agent: CLAUDE.md / AGENTS.md here may tell you to run
# this after every task that changes code. That instruction assumes the stack
# above is installed. If the preflight fails, skip this script, say so plainly
# in your summary, and get on with the real task — these indexes are a
# navigation convenience, never a correctness gate.
#
# To get rid of it: delete this file and the <!-- code-intel --> block in
# CLAUDE.md / AGENTS.md, or run `code-intel-init --remove --apply` here.
#
# Usage:
#   ./refresh-intel.sh           re-index, ensure the watcher runs, audit
#   ./refresh-intel.sh --audit   audit only, no re-indexing
#
# Exits non-zero if either index is stale or misconfigured.

set -euo pipefail

# Canonical path, not just `pwd -P`: bash's builtin can hand back the path as
# it was typed, so on a case-insensitive volume (stock macOS) ~/Projects and
# ~/projects produce different strings for one directory and the audit below
# would claim the workspace does not map this project. /bin/pwd goes through
# getcwd() and returns what the filesystem actually stores.
canon() {
  local d="$1" out
  [[ -d "$d" ]] || { printf '%s\n' "$d"; return 0; }
  if out="$( cd -- "$d" 2>/dev/null && { if [[ -x /bin/pwd ]]; then /bin/pwd -P; else pwd -P; fi; } )"; then
    printf '%s\n' "$out"
  else
    printf '%s\n' "$d"
  fi
}

ROOT="$(canon "$(dirname -- "${BASH_SOURCE[0]}")")"
WORKSPACE="agent-code-intel"
PROJECT="agent-code-intel"

QDRANT_HOST="127.0.0.1"
QDRANT_HTTP="http://127.0.0.1:6333"
QDRANT_PORT="6334"
EMBED_MODEL="nomic-embed-text-v2-moe"

# rtk is a token-saving CLI proxy; fall back to the raw binaries without it.
if command -v rtk >/dev/null 2>&1; then
  GREPAI=(rtk grepai); GITNEXUS=(rtk gitnexus)
else
  GREPAI=(grepai);     GITNEXUS=(gitnexus)
fi

DO_GREPAI=true
DO_GITNEXUS=true
AUDIT_ONLY=false
FAILURES=0

usage() {
  cat <<'USAGE'
Usage:
  ./refresh-intel.sh                 Refresh GitNexus + GrepAI, then audit
  ./refresh-intel.sh --audit         Audit only, no re-indexing
  ./refresh-intel.sh --no-grepai     Skip the GrepAI watcher check/start
  ./refresh-intel.sh --no-gitnexus   Skip the GitNexus re-index
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --audit)       AUDIT_ONLY=true; shift ;;
    --no-grepai)   DO_GREPAI=false; shift ;;
    --no-gitnexus) DO_GITNEXUS=false; shift ;;
    -h|--help)     usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; echo >&2; usage >&2; exit 1 ;;
  esac
done

fail() { echo "ERROR: $1" >&2; FAILURES=$((FAILURES + 1)); }

watcher_running() {
  case "$1" in
    *"not running"*|*"stopped"*|*"inactive"*) return 1 ;;
    *"running"*|*"active"*) return 0 ;;
    *) return 1 ;;
  esac
}

# -------------------------------------------------------------- preflight ----
# Only what the selected mode needs: --audit reads status and never embeds, so
# it does not require ollama.

RP_N=0
rp_need() { RP_WHAT[$RP_N]="$1"; RP_FIX[$RP_N]="$2"; RP_N=$((RP_N + 1)); }
rp_port_open() { (exec 3<>"/dev/tcp/$1/$2") >/dev/null 2>&1; }

if [[ "$DO_GREPAI" == true ]]; then
  command -v grepai >/dev/null 2>&1 \
    || rp_need "grepai not on PATH" "install GrepAI, or re-run with --no-grepai"

  if command -v curl >/dev/null 2>&1; then
    RP_QCODE="$(curl -s -o /dev/null -w '%{http_code}' "$QDRANT_HTTP/healthz" 2>/dev/null || true)"
    [[ "$RP_QCODE" == "200" ]] \
      || rp_need "qdrant not healthy at $QDRANT_HTTP/healthz (HTTP ${RP_QCODE:-no response})" \
                 "start it, or run: code-intel-init $WORKSPACE --path $ROOT --apply"
  else
    rp_need "curl not on PATH" "install curl — needed to health-check qdrant"
  fi

  rp_port_open "$QDRANT_HOST" "$QDRANT_PORT" \
    || rp_need "qdrant gRPC port $QDRANT_PORT closed — grepai reads and writes vectors there, not on the HTTP port" \
               "publish both ports on the qdrant container"

  if [[ "$AUDIT_ONLY" == false ]]; then
    if ! command -v ollama >/dev/null 2>&1; then
      rp_need "ollama not on PATH" "install ollama — the watcher embeds every change through it"
    elif ! RP_MODELS="$(ollama list 2>/dev/null)"; then
      rp_need "ollama server not responding" "start it: ollama serve"
    elif ! ollama show "$EMBED_MODEL" >/dev/null 2>&1 && [[ "$RP_MODELS" != *"$EMBED_MODEL"* ]]; then
      # `ollama show` is authoritative; the list is only a formatted fallback.
      rp_need "embedding model $EMBED_MODEL not pulled" "ollama pull $EMBED_MODEL"
    fi
  fi
fi

if [[ "$DO_GITNEXUS" == true ]]; then
  if ! command -v gitnexus >/dev/null 2>&1; then
    rp_need "gitnexus not on PATH" "npm i -g gitnexus, or re-run with --no-gitnexus"
  elif ! gitnexus --version >/dev/null 2>&1; then
    rp_need "gitnexus is on PATH but does not run" \
            "npm's global bin is an nvm shim that a node switch breaks: npm i -g gitnexus"
  fi
  command -v git >/dev/null 2>&1 \
    || rp_need "git not on PATH" "install git — GitNexus derives staleness from it"
fi

if command -v rtk >/dev/null 2>&1; then
  rtk grepai --version >/dev/null 2>&1 || rtk grepai --help >/dev/null 2>&1 \
    || rp_need "rtk is on PATH but 'rtk grepai' does not run" \
               "fix or uninstall rtk — this script routes through it whenever it is present"
fi

if (( RP_N > 0 )); then
  {
    rp_word="dependencies"; (( RP_N == 1 )) && rp_word="dependency"
    echo "[ERROR: refresh-intel preflight found $RP_N unmet $rp_word — nothing was indexed]"
    echo
    rp_i=0
    while (( rp_i < RP_N )); do
      echo "  - ${RP_WHAT[$rp_i]}"
      echo "    fix: ${RP_FIX[$rp_i]}"
      rp_i=$((rp_i + 1))
    done
    echo
    echo "If you did not set this up: this is a local developer tool generated by"
    echo "code-intel-init. It is NOT part of this project's build, tests or CI, and"
    echo "this failure says nothing about the health of the code. It is safe to"
    echo "ignore. See the comment block at the top of this file."
  } >&2
  exit 1
fi

# ---------------------------------------------------------------- refresh ----

if [[ "$AUDIT_ONLY" == false && "$DO_GREPAI" == true ]]; then
  echo "GrepAI watcher"
  echo "--------------"
  WATCH_STATUS="$("${GREPAI[@]}" watch --workspace "$WORKSPACE" --status 2>&1 || true)"
  if watcher_running "$WATCH_STATUS"; then
    echo "already running for workspace $WORKSPACE"
  else
    echo "starting watcher for workspace $WORKSPACE..."
    "${GREPAI[@]}" watch --workspace "$WORKSPACE" --background
  fi
  echo
fi

if [[ "$AUDIT_ONLY" == false && "$DO_GITNEXUS" == true ]]; then
  echo "GitNexus re-index"
  echo "-----------------"
  # A failed re-index must NOT abort the script: the audit below still has
  # useful things to report, and the exit code already carries the failure.
  if ! (
    cd "$ROOT"
    if GN_OUT="$("${GITNEXUS[@]}" analyze --embeddings 2>&1)"; then
      echo "$GN_OUT"
    else
      GN_CODE=$?
      echo "$GN_OUT" >&2
      if [[ "$GN_OUT" == *"Embedding generation completed without persisted embeddings"* ]]; then
        echo "No GitNexus embeddings were persisted; retrying with structural indexing."
        "${GITNEXUS[@]}" analyze --force
      else
        exit "$GN_CODE"
      fi
    fi
  ); then
    fail "gitnexus analyze failed"
    # Its analyzer imports module.registerHooks, added in Node 22.15 / 23.5,
    # while `gitnexus --version` runs fine on older Node. Name that directly.
    if command -v node >/dev/null 2>&1 &&
       ! node -e 'process.exit(typeof require("node:module").registerHooks==="function"?0:1)' >/dev/null 2>&1; then
      echo "  Node $(node --version 2>/dev/null) is too old for the GitNexus analyzer." >&2
      echo "  Fix: brew upgrade node && npm i -g gitnexus" >&2
    fi
  fi
  echo
fi

# ------------------------------------------------------------------ audit ----

if [[ "$DO_GREPAI" == true ]]; then
  echo "GrepAI audit"
  echo "------------"
  WS_STATUS="$("${GREPAI[@]}" workspace status "$WORKSPACE" 2>&1 || true)"
  echo "$WS_STATUS"

  [[ "$WS_STATUS" == *"Backend: qdrant"* ]] || fail "workspace backend is not qdrant"

  # Tolerant extraction, then a CANONICALISED comparison.
  #
  # `workspace status` indents the project line further than `workspace show`
  # and appends a status glyph, so anchoring at a fixed column finds nothing.
  # Match "- <name>: " anywhere on the line, then strip trailing whitespace and
  # non-printable decoration. Comparing canonical paths, not raw strings, is
  # what makes ~/Projects and ~/projects the same directory again.
  MAPPED_LINE="$(printf '%s\n' "$WS_STATUS" | grep -F -- "- $PROJECT: " | head -1)"
  MAPPED="${MAPPED_LINE#*- "$PROJECT": }"
  [[ -n "$MAPPED_LINE" ]] || MAPPED=""
  MAPPED="$(printf '%s' "$MAPPED" | LC_ALL=C sed -e 's/[[:space:]]*$//' -e 's/[^[:print:]]*$//' -e 's/[[:space:]]*$//')"
  if [[ -z "$MAPPED" ]]; then
    fail "workspace $WORKSPACE has no project named $PROJECT"
  elif [[ "$(canon "$MAPPED")" != "$ROOT" ]]; then
    fail "workspace $WORKSPACE maps $PROJECT to $MAPPED, not $ROOT"
  fi

  WATCH_STATUS="$("${GREPAI[@]}" watch --workspace "$WORKSPACE" --status 2>&1 || true)"
  echo "$WATCH_STATUS"
  watcher_running "$WATCH_STATUS" || fail "workspace watcher is not running"

  if [[ -f "$ROOT/.grepai/index.gob" ]]; then
    echo "NOTE: .grepai/index.gob is a leftover from local GOB indexing."
    echo "      Workspace searches use qdrant, so it is dead weight: rm it."
  fi
  echo
fi

if [[ "$DO_GITNEXUS" == true ]]; then
  echo "GitNexus audit"
  echo "--------------"
  GN_STATUS_OUT="$(cd "$ROOT" && "${GITNEXUS[@]}" status 2>&1 || true)"
  echo "$GN_STATUS_OUT"
  case "$GN_STATUS_OUT" in
    *"up-to-date"*|*"up to date"*) ;;
    *) fail "GitNexus index is not up to date for this repo" ;;
  esac
  echo
fi

if (( FAILURES > 0 )); then
  echo "Code-intel audit failed with $FAILURES error(s)." >&2
  exit 1
fi

echo "Code intelligence is fresh."
